set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(TOOLCHAIN_ROOT "C:/msys64/mingw64/bin")

set(CMAKE_C_COMPILER "${TOOLCHAIN_ROOT}/clang.exe")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_ROOT}/clang++.exe")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_ROOT}/clang.exe")
set(CMAKE_ASM_NASM_COMPILER "${TOOLCHAIN_ROOT}/nasm.exe")
set(CMAKE_AR "${TOOLCHAIN_ROOT}/ar.exe")
set(CMAKE_RANLIB "${TOOLCHAIN_ROOT}/ranlib.exe")
set(CMAKE_OBJCOPY "${TOOLCHAIN_ROOT}/objcopy.exe")
set(CMAKE_LINKER "${TOOLCHAIN_ROOT}/lld.exe")

set(CMAKE_C_COMPILER_TARGET x86_64-elf)
set(CMAKE_CXX_COMPILER_TARGET x86_64-elf)
set(CMAKE_ASM_NASM_OBJECT_FORMAT elf64)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
